spring:
  application:
    name: demenage
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin123
  main:
    allow-circular-references: true
app:
  security:
    jwt:
      keystore-location: keys/keystore.p12
      keystore-password: changeit
      key-alias: jwt-sign-key
      private-key-passphrase: changeit

server:
  port: ${PORT:4500}

logging:
  level:
    root: INFO
  file:
    name: app.log
    path: /var/logs/myapp
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
