spring:
  application:
    name: demenage
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: admin
      password: admin123
  main:
    allow-circular-references: true

server:
  port: ${PORT:4500}
